/**
 * Supabase Database Schema (SQL DDL)
 *
 * Run this in your Supabase SQL editor to create the leaderboards table.
 * Then create a storage bucket named "avatars" and set CORS policies.
 *
 * VITE .env.local:
 * VITE_SUPABASE_URL=https://your-project.supabase.co
 * VITE_SUPABASE_ANON_KEY=your-anon-key
 */

-- ============================================================================
-- LEADERBOARD TABLE
-- ============================================================================

CREATE TABLE leaderboards (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  player_name TEXT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  avatar_url TEXT,
  CONSTRAINT valid_score CHECK (score >= 0 AND score <= 999999),
  CONSTRAINT valid_name_length CHECK (char_length(player_name) >= 1 AND char_length(player_name) <= 50)
);

-- Indexes for performance
CREATE INDEX idx_leaderboards_score ON leaderboards(score DESC);
CREATE INDEX idx_leaderboards_player_name ON leaderboards(LOWER(player_name));
CREATE INDEX idx_leaderboards_created_at ON leaderboards(created_at DESC);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on table
ALTER TABLE leaderboards ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read leaderboard
CREATE POLICY "leaderboards_read_all" ON leaderboards
  FOR SELECT USING (true);

-- Allow anonymous inserts (score submission)
-- In production, you may want to add rate limiting or require auth
CREATE POLICY "leaderboards_insert_anonymous" ON leaderboards
  FOR INSERT WITH CHECK (true);

-- ============================================================================
-- STORAGE BUCKET - AVATARS
-- ============================================================================

-- Create storage bucket (via Supabase dashboard):
-- 1. Go to Storage > Buckets
-- 2. Create new bucket named "avatars"
-- 3. Make it PUBLIC
-- 4. Set CORS policy (allow your domain)

-- CORS Policy for bucket (use in bucket settings):
-- [
--   {
--     "origin": ["https://yourdomain.com", "http://localhost:5173"],
--     "methods": ["GET", "POST"],
--     "allowedHeaders": ["content-type", "authorization"],
--     "maxAgeSeconds": 3600
--   }
-- ]

-- ============================================================================
-- VIEWS (OPTIONAL)
-- ============================================================================

-- View: Top 100 scores (for easier queries)
CREATE VIEW leaderboard_top_100 AS
SELECT
  ROW_NUMBER() OVER (ORDER BY score DESC) as rank,
  player_name,
  score,
  avatar_url,
  created_at
FROM leaderboards
ORDER BY score DESC
LIMIT 100;

-- View: Daily leaderboard (scores from today)
CREATE VIEW leaderboard_daily AS
SELECT
  ROW_NUMBER() OVER (ORDER BY score DESC) as rank,
  player_name,
  score,
  avatar_url,
  created_at
FROM leaderboards
WHERE DATE(created_at) = CURRENT_DATE
ORDER BY score DESC;

-- ============================================================================
-- FUNCTIONS (OPTIONAL - FOR REAL-TIME UPDATES)
-- ============================================================================

-- Realtime listening example (client-side usage):
-- supabase
--   .from('leaderboards')
--   .on('*', payload => console.log('Score submitted!', payload))
--   .subscribe();
